INSERT INTO metrics.records_duplicates (record, metric, day, dup) VALUES('2222', 'cat1', '2017-04-24 00:00', 5);
INSERT INTO metrics.records_duplicates (record, metric, day, dup) VALUES('2222', 'cat2', '2017-04-24 00:00', 10);
INSERT INTO metrics.records_duplicates (record, metric, day, dup) VALUES('4444', 'cat1', '2017-04-24 00:00', 1);
INSERT INTO metrics.records_duplicates (record, metric, day, dup) VALUES('4444', 'cat1', '2017-04-26 00:00', 300);
