INSERT INTO metrics.records (record, time, metric) VALUES('2222', '2017-04-24 12:35', 'cat1');
INSERT INTO metrics.records (record, time, metric) VALUES('2222', '2017-04-24 12:35', 'cat2');
INSERT INTO metrics.records (record, time, metric) VALUES('2222', '2017-04-24 12:40', 'cat1');
INSERT INTO metrics.records (record, time, metric) VALUES('2222', '2017-04-24 12:50', 'cat1');
INSERT INTO metrics.records (record, time, metric) VALUES('4444', '2017-04-24 12:50', 'cat1');
